# Generated by Django 6.1 on 2026-09-01 11:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('assignee_email', models.EmailField(max_length=254)),
                ('deadline', models.DateTimeField()),
                ('status', models.CharField(choices=[('PD', 'Pending'), ('CP', 'Completed'), ('OD', 'Overdue')], default='PD', max_length=2)),
                ('completion_notes', models.TextField(blank=True)),
                ('completion_file', models.FileField(blank=True, null=True, upload_to='mission_files/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_submission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='missions', to='uploads.imagesubmission')),
            ],
        ),
    ]
